name: Docker Build (Single Profile Mode)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (e.g., v1.0.0-single)'
        required: false
        default: 'single-profile-latest'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'bun.lockb'
      - 'Dockerfile'
      - '.github/workflows/docker-single-profile.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            suffix=-single-profile,onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{ github.event.inputs.tag || 'single-profile-latest' }}
            type=raw,value=single-profile-{{date 'YYYYMMDD-HHmmss'}}
            type=sha,prefix=single-profile-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_SINGLE_PROFILE_MODE=true
            SINGLE_PROFILE_MODE=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false